# Logging configuration
logging:
  version: 1.1
  formatters:
    yfin:
      format: "yfin Transformer - %(asctime)s - %(funcName)s - %(levelname)s - %(message)s"
  file:
      filename: 'logs/yfin.logs'
  root:
    level: DEBUG
    handlers: [console]